# SPDX-FileCopyrightText: 2023 Jose D. Montoya
#
# SPDX-License-Identifier: Unlicense

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3"

python:
  install:
    - requirements: docs/requirements.txt
